spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardgamerent
    username: evgen
    password: '{cipher}47a91a4c7904957dafe5ae6f347f390e15a49791ae9e7dd5d41964f37cc381db'
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration/mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  profile:
    info: src/main/resources/log4j_info.properties
    debug: src/main/resources/log4j_debug.properties

jwt:
  secret: konoplyanik
  expiration: 7200000
  issuer: itrex
